
services:
  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - DATABASE_SECRET=${DATABASE_SECRET}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect

  spring-app:
    image: cardapio-api:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/cardapio
    depends_on:
      - postgres-db

  spa-app:
    build:
      context: ./cardapioF
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - spring-app
